export { healthResponseSchema } from "./health"
export type { HealthResponse } from "./health"
export { apiErrorSchema } from "./error"
export type { ApiError } from "./error"
export { availabilitySlotSchema, availabilityResponseSchema } from "./availability"
export type { AvailabilitySlot, AvailabilityResponse } from "./availability"
